export const liquidGlassCardControls = {
  refThickness: 20,
  refFactor: 1.4,
  refDispersion: 0,
  refFresnelRange: 0,
  refFresnelHardness: 0,
  refFresnelFactor: 0,
  glareRange: 0,
  glareHardness: 0,
  glareFactor: 0,
  glareConvergence: 0,
  glareOppositeFactor: 0,
  glareAngle: -45,
  blurRadius: 50,
  blurEdge: false,
  tint: {
    r: 255,
    g: 255,
    b: 255,
    a: 0,
  },
  shadowExpand: 0,
  shadowFactor: 0,
  shadowPosition: {
    x: 0,
    y: 0,
  },
  bgType: 4,
  shapeWidth: 200,
  shapeHeight: 200,
  shapeRadius: 50.1,
  shapeRoundness: 2,
  mergeRate: 0,
  showShape1: true,
  springSizeFactor: 0,
  step: 9,
} as const;
