export const LIQUID_GLASS_STUDIO_CONFIG = {
  source: "iyinchao/liquid-glass-studio",
  version: "1.0.0",
  timestamp: "2026-07-11T05:07:03.871Z",
  exportFile: "liquid-glass-2026-07-11T05-07-03.json",
  renderer: "webgpu",
  language: "zh-CN",
  refThickness: 20,
  refFactor: 1.4,
  refDispersion: 7,
  refFresnelRange: 14,
  refFresnelHardness: 35,
  refFresnelFactor: 20,
  glareRange: 14,
  glareHardness: 35,
  glareFactor: 90,
  glareConvergence: 50,
  glareOppositeFactor: 80,
  glareAngle: -45,
  blurRadius: 20,
  blurEdge: true,
  tint: { r: 255, g: 255, b: 255, a: 0 },
  shadowExpand: 25,
  shadowFactor: 15,
  shadowPosition: { x: 0, y: -10 },
  bgType: 2,
  // Keep original geometry — button stays a true circle; panel uses live layout size.
  shapeWidth: 200,
  shapeHeight: 200,
  shapeRadius: 50.1,
  shapeRoundness: 2,
  mergeRate: 0.1,
  showShape1: true,
  springSizeFactor: 3.07,
  step: 9,
} as const;

export function getLiquidGlassStudioUniforms() {
  const config = LIQUID_GLASS_STUDIO_CONFIG;

  return {
    refThickness: config.refThickness,
    refFactor: config.refFactor,
    refDispersion: config.refDispersion,
    fresnelRange: config.refFresnelRange,
    fresnelHardness: config.refFresnelHardness / 100,
    fresnelFactor: config.refFresnelFactor / 100,
    glareRange: config.glareRange,
    glareHardness: config.glareHardness / 100,
    glareFactor: Number((config.glareFactor / 100).toFixed(4)),
    glareConvergence: config.glareConvergence / 100,
    glareOppositeFactor: config.glareOppositeFactor / 100,
    glareAngle: (config.glareAngle * Math.PI) / 180,
    blurRadius: config.blurRadius,
    tint: [
      config.tint.r / 255,
      config.tint.g / 255,
      config.tint.b / 255,
      config.tint.a,
    ] as [number, number, number, number],
    shadowExpand: config.shadowExpand,
    shadowFactor: config.shadowFactor / 100,
  };
}
